image: mhart/alpine-node:10

pipelines:
  default:
    - parallel:
      - step:
          name: Build and test API
          caches:
            - node
          script:
            - chmod +x ./api/build-test.sh
            - ./api/build-test.sh
      - step:
          name: Build and test React App
          caches:
            - node
          script:
            - chmod +x ./client/build-test.sh
            - ./client/build-test.sh
      