image: mhart/alpine-node:10

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - chmod +x ./api/build-test.sh
          - ./api/build-test.sh
      