service: jobscrape

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http: 'ANY {proxy+}'
