service: jobscrape

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true
